# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuredialog.ui'
#
# Created: Thu Jun  5 20:55:07 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 449)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.configGroupBox = QtGui.QGroupBox(Dialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label0 = QtGui.QLabel(self.configGroupBox)
        self.label0.setObjectName("label0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label0)
        self.lineEdit0 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit0.setObjectName("lineEdit0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit0)
        self.label9 = QtGui.QLabel(self.configGroupBox)
        self.label9.setObjectName("label9")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label9)
        self.comboBoxDistanceMode = QtGui.QComboBox(self.configGroupBox)
        self.comboBoxDistanceMode.setObjectName("comboBoxDistanceMode")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxDistanceMode)
        self.label1 = QtGui.QLabel(self.configGroupBox)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label1)
        self.label2 = QtGui.QLabel(self.configGroupBox)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label2)
        self.label3 = QtGui.QLabel(self.configGroupBox)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label3)
        self.label4 = QtGui.QLabel(self.configGroupBox)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label4)
        self.label5 = QtGui.QLabel(self.configGroupBox)
        self.label5.setObjectName("label5")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label5)
        self.label8 = QtGui.QLabel(self.configGroupBox)
        self.label8.setObjectName("label8")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label8)
        self.label10 = QtGui.QLabel(self.configGroupBox)
        self.label10.setObjectName("label10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label10)
        self.label14 = QtGui.QLabel(self.configGroupBox)
        self.label14.setObjectName("label14")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label14)
        self.checkBoxGUI = QtGui.QCheckBox(self.configGroupBox)
        self.checkBoxGUI.setText("")
        self.checkBoxGUI.setObjectName("checkBoxGUI")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.checkBoxGUI)
        self.checkBoxFitSize = QtGui.QCheckBox(self.configGroupBox)
        self.checkBoxFitSize.setText("")
        self.checkBoxFitSize.setObjectName("checkBoxFitSize")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.checkBoxFitSize)
        self.spinBoxPCsToFit = QtGui.QSpinBox(self.configGroupBox)
        self.spinBoxPCsToFit.setObjectName("spinBoxPCsToFit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxPCsToFit)
        self.spinBoxSurfDisc = QtGui.QSpinBox(self.configGroupBox)
        self.spinBoxSurfDisc.setObjectName("spinBoxSurfDisc")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.spinBoxSurfDisc)
        self.doubleSpinBoxMWeight = QtGui.QDoubleSpinBox(self.configGroupBox)
        self.doubleSpinBoxMWeight.setObjectName("doubleSpinBoxMWeight")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxMWeight)
        self.spinBoxMaxfev = QtGui.QSpinBox(self.configGroupBox)
        self.spinBoxMaxfev.setObjectName("spinBoxMaxfev")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.spinBoxMaxfev)
        self.spinBoxNCP = QtGui.QSpinBox(self.configGroupBox)
        self.spinBoxNCP.setObjectName("spinBoxNCP")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.spinBoxNCP)
        self.lineEditXTol = QtGui.QLineEdit(self.configGroupBox)
        self.lineEditXTol.setObjectName("lineEditXTol")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEditXTol)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "ConfigureDialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label0.setText(QtGui.QApplication.translate("Dialog", "identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label9.setText(QtGui.QApplication.translate("Dialog", "Distance Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("Dialog", "PCs to Fit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Surface Discretisation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setText(QtGui.QApplication.translate("Dialog", "Mahalanobis Weight:", None, QtGui.QApplication.UnicodeUTF8))
        self.label4.setText(QtGui.QApplication.translate("Dialog", "Max Func Eval:", None, QtGui.QApplication.UnicodeUTF8))
        self.label5.setText(QtGui.QApplication.translate("Dialog", "xtol:", None, QtGui.QApplication.UnicodeUTF8))
        self.label8.setText(QtGui.QApplication.translate("Dialog", "Fit Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label10.setText(QtGui.QApplication.translate("Dialog", "N Closest Points:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label14.setText(QtGui.QApplication.translate("Dialog", "GUI:", None, QtGui.QApplication.UnicodeUTF8))

