# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuredialog.ui'
#
# Created: Wed Jan  8 11:07:25 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 543)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.configGroupBox = QtGui.QGroupBox(Dialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.label0 = QtGui.QLabel(self.configGroupBox)
        self.label0.setObjectName("label0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label0)
        self.lineEdit0 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit0.setObjectName("lineEdit0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit0)
        self.label1 = QtGui.QLabel(self.configGroupBox)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label1)
        self.lineEdit1 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit1.setObjectName("lineEdit1")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit1)
        self.label2 = QtGui.QLabel(self.configGroupBox)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label2)
        self.lineEdit2 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit2.setObjectName("lineEdit2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit2)
        self.label3 = QtGui.QLabel(self.configGroupBox)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label3)
        self.lineEdit3 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit3.setObjectName("lineEdit3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit3)
        self.label4 = QtGui.QLabel(self.configGroupBox)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label4)
        self.lineEdit4 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit4.setObjectName("lineEdit4")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit4)
        self.label5 = QtGui.QLabel(self.configGroupBox)
        self.label5.setObjectName("label5")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label5)
        self.lineEdit5 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit5.setObjectName("lineEdit5")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit5)
        self.label6 = QtGui.QLabel(self.configGroupBox)
        self.label6.setObjectName("label6")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label6)
        self.lineEdit6 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit6.setObjectName("lineEdit6")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit6)
        self.label7 = QtGui.QLabel(self.configGroupBox)
        self.label7.setObjectName("label7")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label7)
        self.lineEdit7 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit7.setObjectName("lineEdit7")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEdit7)
        self.label8 = QtGui.QLabel(self.configGroupBox)
        self.label8.setObjectName("label8")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label8)
        self.lineEdit8 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit8.setObjectName("lineEdit8")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit8)
        self.label9 = QtGui.QLabel(self.configGroupBox)
        self.label9.setObjectName("label9")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label9)
        self.lineEdit9 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit9.setObjectName("lineEdit9")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit9)
        self.lineEdit11 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit11.setObjectName("lineEdit11")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEdit11)
        self.label11 = QtGui.QLabel(self.configGroupBox)
        self.label11.setObjectName("label11")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label11)
        self.lineEdit10 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit10.setObjectName("lineEdit10")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEdit10)
        self.label10 = QtGui.QLabel(self.configGroupBox)
        self.label10.setObjectName("label10")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label10)
        self.lineEdit12 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit12.setObjectName("lineEdit12")
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEdit12)
        self.label12 = QtGui.QLabel(self.configGroupBox)
        self.label12.setObjectName("label12")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label12)
        self.lineEdit13 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit13.setObjectName("lineEdit13")
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEdit13)
        self.label13 = QtGui.QLabel(self.configGroupBox)
        self.label13.setObjectName("label13")
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.label13)
        self.label14 = QtGui.QLabel(self.configGroupBox)
        self.label14.setObjectName("label14")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label14)
        self.lineEdit14 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit14.setObjectName("lineEdit14")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit14)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "ConfigureDialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label0.setText(QtGui.QApplication.translate("Dialog", "identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("Dialog", "mesh discretisation:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "sobelov discretisaton:", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setText(QtGui.QApplication.translate("Dialog", "sobelov weight:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label4.setText(QtGui.QApplication.translate("Dialog", "normal discretisation:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label5.setText(QtGui.QApplication.translate("Dialog", "normal weight:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label6.setText(QtGui.QApplication.translate("Dialog", "max sub-iterations:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label7.setText(QtGui.QApplication.translate("Dialog", "xtol:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label8.setText(QtGui.QApplication.translate("Dialog", "max iterations:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label9.setText(QtGui.QApplication.translate("Dialog", "fit mode:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label11.setText(QtGui.QApplication.translate("Dialog", "kdtree args:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label10.setText(QtGui.QApplication.translate("Dialog", "n closest points:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label12.setText(QtGui.QApplication.translate("Dialog", "verbose:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label13.setText(QtGui.QApplication.translate("Dialog", "fixed nodes:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label14.setText(QtGui.QApplication.translate("Dialog", "GUI:", None, QtGui.QApplication.UnicodeUTF8))

